name: sgs_sha
description: "A translation and rule clarification app for San Guo Sha (SGS/三国杀)"
publish_to: 'github'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  lpinyin: ^2.0.3
  shared_preferences: ^2.2.2
  camera: ^0.10.5+9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/data/generals/
    - assets/data/library/
    - assets/data/ruleset/
    - assets/images/
    - assets/images/generals/
    - assets/images/library/
    