// lib/core/services/image_embedding_matcher.dart
//
// MobileNetV2 Feature Embedding Matcher — Phase 9
//
// Replaces pHash (image_hash_matcher.dart) with CNN feature embeddings
// for robust cross-domain image matching (card photo vs clean artwork).
//
// Architecture:
//   - MobileNetV2 (ImageNet-pretrained) extracts a 1280-dim feature vector
//     from the penultimate layer (global average pooling output)
//   - Feature vectors are L2-normalised → cosine similarity = dot product
//   - Reference embeddings for all generals are pre-computed at build time
//     and shipped as a binary asset (assets/data/general_embeddings.bin)
//   - At scan time, one forward pass (~30ms on mid-range phone) extracts
//     the query embedding, then 468 dot products take <1ms total
//
// Dependencies:
//   - tflite_flutter: ^0.11.0 (runs MobileNetV2 on-device via TFLite)
//   - image: (already in pubspec — used for resize/decode)
//
// Asset files required:
//   - assets/models/mobilenet_v2.tflite (~14MB, MobileNetV2 feature extractor)
//   - assets/data/general_embeddings.bin (pre-computed, generated by
//     tools/generate_embeddings.py)
//
// The pre-computed embeddings file format:
//   - 4 bytes: entry count (uint32, little-endian)
//   - For each entry:
//       - 4 bytes: ID string length (uint32, little-endian)
//       - N bytes: ID string (UTF-8, e.g. "YJ_WU033")
//       - 5120 bytes: 1280 × float32 embedding (little-endian)

import 'dart:math' as math;

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:image/image.dart' as img;
import 'package:tflite_flutter/tflite_flutter.dart';

/// Embedding vector dimensionality (MobileNetV2 penultimate layer).
const int _embeddingDim = 1280;

/// MobileNetV2 input size.
const int _inputSize = 224;

/// ImageNet mean/std for normalisation.
const _imagenetMean = [0.485, 0.456, 0.406];
const _imagenetStd = [0.229, 0.224, 0.225];

class ImageEmbeddingMatcher {
  ImageEmbeddingMatcher._();
  static final ImageEmbeddingMatcher instance = ImageEmbeddingMatcher._();

  Interpreter? _interpreter;
  bool _modelLoaded = false;

  /// Pre-computed reference embeddings keyed by card ID (e.g. "YJ_WU033").
  /// Loaded from assets/data/general_embeddings.bin at warmup.
  final Map<String, Float32List> _referenceEmbeddings = {};

  /// In-memory cache for runtime-computed embeddings (query images).
  /// Keyed by asset path for consistency with the old ImageHashMatcher API.
  final Map<String, Float32List> _runtimeCache = {};

  // ═════════════════════════════════════════════════════════════════════════
  // INITIALISATION
  // ═════════════════════════════════════════════════════════════════════════

  /// Loads the TFLite model and pre-computed reference embeddings.
  /// Call once during app startup or scanner warmup.
  Future<void> loadModel() async {
    if (_modelLoaded) return;
    try {
      _interpreter = await Interpreter.fromAsset('models/mobilenet_v2.tflite');
      debugPrint('[Embedding] Model loaded: '
          'input=${_interpreter!.getInputTensor(0).shape}, '
          'output=${_interpreter!.getOutputTensor(0).shape}');
      _modelLoaded = true;
    } catch (e) {
      debugPrint('[Embedding] Failed to load model: $e');
    }
  }

  /// Loads pre-computed reference embeddings from the binary asset.
  /// These are generated by tools/generate_embeddings.py at build time.
  Future<void> loadReferenceEmbeddings() async {
    try {
      final data = await rootBundle.load('assets/data/general_embeddings.bin');
      final bytes = data.buffer.asByteData();
      int offset = 0;

      final count = bytes.getUint32(offset, Endian.little);
      offset += 4;

      for (var i = 0; i < count; i++) {
        // Read ID string
        final idLen = bytes.getUint32(offset, Endian.little);
        offset += 4;
        final idBytes = data.buffer.asUint8List(offset, idLen);
        final id = String.fromCharCodes(idBytes);
        offset += idLen;

        // Read 1280 × float32 embedding
        final embedding = Float32List(_embeddingDim);
        for (var j = 0; j < _embeddingDim; j++) {
          embedding[j] = bytes.getFloat32(offset, Endian.little);
          offset += 4;
        }
        _referenceEmbeddings[id] = embedding;
      }

      debugPrint('[Embedding] Loaded ${_referenceEmbeddings.length} '
          'reference embeddings.');
    } catch (e) {
      debugPrint('[Embedding] Failed to load reference embeddings: $e '
          '(run tools/generate_embeddings.py to create the file)');
    }
  }

  bool get isReady => _modelLoaded;
  int get referenceCount => _referenceEmbeddings.length;

  // ═════════════════════════════════════════════════════════════════════════
  // PUBLIC API (compatible with old ImageHashMatcher interface)
  // ═════════════════════════════════════════════════════════════════════════

  /// Computes the feature embedding of [bytes] (JPEG/WebP/PNG).
  /// Returns null if the model isn't loaded or decoding fails.
  Float32List? embeddingFromBytes(Uint8List bytes) {
    final decoded = img.decodeImage(bytes);
    if (decoded == null || !_modelLoaded) return null;
    return _computeEmbedding(decoded);
  }

  /// Computes the feature embedding of an already-decoded [image].
  Float32List? embeddingFromImage(img.Image image) {
    if (!_modelLoaded) return null;
    return _computeEmbedding(image);
  }

  /// Returns the pre-computed reference embedding for [cardId].
  /// Returns null if the card wasn't in the pre-computed set.
  Float32List? getReferenceEmbedding(String cardId) {
    return _referenceEmbeddings[cardId];
  }

  /// Returns the cached embedding for [assetPath] (runtime cache).
  /// Used by the background caching loop for API compatibility.
  Float32List? getCachedHash(String assetPath) => _runtimeCache[assetPath];

  /// Loads and caches the embedding for [assetPath].
  /// Used by the background caching loop.
  Future<Float32List?> hashFromAsset(String assetPath) async {
    if (_runtimeCache.containsKey(assetPath)) return _runtimeCache[assetPath];
    if (!_modelLoaded) return null;
    try {
      final data = await rootBundle.load(assetPath);
      final bytes = data.buffer.asUint8List();
      final decoded = img.decodeImage(bytes);
      if (decoded == null) return null;
      final embedding = _computeEmbedding(decoded);
      if (embedding != null) {
        _runtimeCache[assetPath] = embedding;
      }
      return embedding;
    } catch (_) {
      return null;
    }
  }

  /// Cosine similarity between two L2-normalised embeddings ∈ [0.0, 1.0].
  ///
  /// Since both vectors are L2-normalised, cosine similarity = dot product.
  /// Mapped from [-1, 1] → [0, 1] via (dot + 1) / 2 for consistency with
  /// the old pHash similarity API where 1.0 = identical.
  ///
  /// Expected similarity ranges:
  ///   ≥ 0.85: same artwork, different framing/lighting
  ///   0.70–0.85: visually similar (same character, different pose)
  ///   0.50–0.70: somewhat similar (same colour palette/faction)
  ///   < 0.50: clearly different characters
  double similarity(Float32List embA, Float32List embB) {
    if (embA.length != embB.length) return 0.0;
    double dot = 0.0;
    for (var i = 0; i < embA.length; i++) {
      dot += embA[i] * embB[i];
    }
    // Both are L2-normalised, so dot ∈ [-1, 1]. Map to [0, 1].
    return ((dot + 1.0) / 2.0).clamp(0.0, 1.0);
  }

  /// Finds the top [k] most similar reference cards to [queryEmbedding].
  /// Returns a list of (cardId, similarity) pairs sorted descending.
  ///
  /// This is O(n) where n = number of reference embeddings (~468).
  /// At 1280-dim dot product per candidate, total time is <1ms.
  List<(String, double)> findTopK(Float32List queryEmbedding, {int k = 5}) {
    final scores = <(String, double)>[];
    for (final entry in _referenceEmbeddings.entries) {
      final sim = similarity(queryEmbedding, entry.value);
      scores.add((entry.key, sim));
    }
    scores.sort((a, b) => b.$2.compareTo(a.$2));
    return scores.take(k).toList();
  }

  void clearCache() {
    _runtimeCache.clear();
  }

  void dispose() {
    _interpreter?.close();
    _interpreter = null;
    _modelLoaded = false;
  }

  // ═════════════════════════════════════════════════════════════════════════
  // EMBEDDING COMPUTATION
  // ═════════════════════════════════════════════════════════════════════════

  Float32List? _computeEmbedding(img.Image source) {
    if (_interpreter == null) return null;

    // Step 1: Resize to 224×224
    final resized = img.copyResize(source, width: _inputSize, height: _inputSize);

    // Step 2: Build input tensor [1, 224, 224, 3] with ImageNet normalisation
    final input = List.generate(
      1,
      (_) => List.generate(
        _inputSize,
        (y) => List.generate(
          _inputSize,
          (x) {
            final pixel = resized.getPixel(x, y);
            return [
              (pixel.r.toDouble() / 255.0 - _imagenetMean[0]) / _imagenetStd[0],
              (pixel.g.toDouble() / 255.0 - _imagenetMean[1]) / _imagenetStd[1],
              (pixel.b.toDouble() / 255.0 - _imagenetMean[2]) / _imagenetStd[2],
            ];
          },
        ),
      ),
    );

    // Step 3: Run inference
    final outputShape = _interpreter!.getOutputTensor(0).shape;
    final outputSize = outputShape.last;
    final output = List.generate(1, (_) => List<double>.filled(outputSize, 0));

    try {
      _interpreter!.run(input, output);
    } catch (e) {
      debugPrint('[Embedding] Inference error: $e');
      return null;
    }

    // Step 4: L2-normalise the output vector
    final embedding = Float32List(outputSize);
    double norm = 0.0;
    for (var i = 0; i < outputSize; i++) {
      embedding[i] = output[0][i];
      norm += embedding[i] * embedding[i];
    }
    norm = math.sqrt(norm);
    if (norm > 1e-10) {
      for (var i = 0; i < outputSize; i++) {
        embedding[i] /= norm;
      }
    }

    return embedding;
  }
}